# Screen-related constants
TILEWIDTH = 16
TILEHEIGHT = 16
NROWS = 36
NCOLS = 28
SCREENWIDTH = NCOLS * TILEWIDTH
SCREENHEIGHT = NROWS * TILEHEIGHT
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)

# Colours (R, G, B)
BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)

# Directions
STOP = 0 # None
UP = 1
DOWN = -1
LEFT = 2
RIGHT = -2
PORTAL = 3

# Game Objects
PACMAN = 0
PELLET = 1
POWERPELLET = 2
